services:
  - type: web
    name: investopilot
    env: node
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Required: PostgreSQL connection string - Set in Render dashboard
      # Additional required env vars to set in Render dashboard:
      # - SESSION_SECRET: Random secret for session encryption
      # - PASSWORD_PEPPER: Random string for password security
      # - SENDGRID_API_KEY: For sending emails (optional)
      # - FRONTEND_URL: Your deployed app URL (e.g., https://yourdomain.onrender.com)
      # - GROQ_API_KEY: For AI chat features (optional)
      # - LOG_LEVEL: Logging verbosity (default: info)
    plan: free
    autoDeploy: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
